spring.application.name=distributed-booking
server.port=8080

# Cấu hình mặc định cho Server ID (Sẽ bị ghi đè khi lên Render)
server.id=Local-Server
peer.servers=http://localhost:8081,http://localhost:8082

# Tắt cache Thymeleaf để dev cho nhanh
spring.thymeleaf.cache=false
# Kết nối MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://dluu5032_db_user:Mvt7lR6jK0INhlo6@cluster0.rw2nn1s.mongodb.net/FlightDB?retryWrites=true&w=majority